databases:
  - name: Lincoln
    databaseName: littlelemondb
    user: littlelemondb_user

services:
  - type: web
    name: littlelemon
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn littlelemon.wsgi:application"
    envVars:
      - key: postgres://littlelemondb_user:vBO1rmEbqaomIaHbD2YQoR2shSDISDIt@dpg-ckd175ect0pc73cgv3og-a/littlelemondb
        fromDatabase:
          name: littleleomn
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
